version: "3"

services:

  db:
    image: customer_care/db
    build: 
      context: database
      dockerfile: database.Dockerfile
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
        - ../.env

  server:
    image: customer_care/prod/server
    build:
      context: ..
      dockerfile: ./Docker/server/server.dev.Dockerfile
    ports:
      - "127.0.0.1:7878:7878" 

volumes: 
  pgdata:
